authapp/urls.py
from django.urls import path

from .views import login, logout, RegisterCreateView

app_name = 'authapp'

urlpatterns = [
    # path('login/', login, name='login'),
    path('', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', RegisterCreateView.as_view(), name='register'),
]

info/urls.py
from django.urls import path

from .views import index, study, studying

app_name = 'info'

urlpatterns = [
    path('study/', study, name='study'),
    path('studying/', studying, name='studying'),
    path('', index, name='index'),
    # path('', index, name='index'),
]

sdo/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('info.urls', namespace='info'), name='index'),
    path('info/', include('info.urls', namespace='info'), name='index'),
    path('tests/', include('tests.urls', namespace='tests'), name='test'),
    path('studyapp/', include('studyapp.urls', namespace='studyapp'), name='study'),
    # path('auth/', include('authapp.urls', namespace='authapp'), name='auth'),
    path('', include('authapp.urls', namespace='authapp'), name='auth'),
]

studyapp/urls.py
from django.urls import path

from .views import study_start, topic_1_1, topic_1_2, topic_1_3, topic_1_4, topic_1_5, topics, topic_2_1, topic_2_2, \
    topic_2_3, topic_2_4, topic_3_1, topic_3_2, topic_3_3, topic_3_4, topic_3_5, topic_3_6, topic_4_1, topic_4_2, \
    topic_4_3, topic_4_4, topic_4_5, topic_4_6, topic_4_7, topic_4_8, topic_4_9, topic_5_0, topic_5_1, topic_5_2, \
    topic_5_3, topic_5_4, topic_5_5, topic_5_6, topic_5_7, topic_5_8, topic_5_9, topic_5_10, topic_5_11, topic_5_12, \
    topic_5_13, topic_5_14, topics_b, topics_c, topics_d, topics_e

app_name = 'studyapp'

urlpatterns = [
    path('', study_start, name='study_start'),
    # path('test-a', test_a, name='test_a'),
    path('topics', topics, name='topics'),
    path('topics-b', topics_b, name='topics_b'),
    path('topics-c', topics_c, name='topics_c'),
    path('topics-d', topics_d, name='topics_d'),
    path('topics-e', topics_e, name='topics_e'),
    path('topic-1-1', topic_1_1, name='topic_1_1'),
    path('topic-1-2', topic_1_2, name='topic_1_2'),
    path('topic-1-3', topic_1_3, name='topic_1_3'),
    path('topic-1-4', topic_1_4, name='topic_1_4'),
    path('topic-1-5', topic_1_5, name='topic_1_5'),
    path('topic-2-1', topic_2_1, name='topic_2_1'),
    path('topic-2-2', topic_2_2, name='topic_2_2'),
    path('topic-2-3', topic_2_3, name='topic_2_3'),
    path('topic-2-4', topic_2_4, name='topic_2_4'),
    path('topic-3-1', topic_3_1, name='topic_3_1'),
    path('topic-3-2', topic_3_2, name='topic_3_2'),
    path('topic-3-3', topic_3_3, name='topic_3_3'),
    path('topic-3-4', topic_3_4, name='topic_3_4'),
    path('topic-3-5', topic_3_5, name='topic_3_5'),
    path('topic-3-6', topic_3_6, name='topic_3_6'),
    # path('topic-3-7', topic_3_7, name='topic_3_7'),
    # path('topic-3-8', topic_3_8, name='topic_3_8'),
    path('topic-4-1', topic_4_1, name='topic_4_1'),
    path('topic-4-2', topic_4_2, name='topic_4_2'),
    path('topic-4-3', topic_4_3, name='topic_4_3'),
    path('topic-4-4', topic_4_4, name='topic_4_4'),
    path('topic-4-5', topic_4_5, name='topic_4_5'),
    path('topic-4-6', topic_4_6, name='topic_4_6'),
    path('topic-4-7', topic_4_7, name='topic_4_7'),
    path('topic-4-8', topic_4_8, name='topic_4_8'),
    path('topic-4-9', topic_4_9, name='topic_4_9'),
    path('topic-5-0', topic_5_0, name='topic_5_0'),
    path('topic-5-1', topic_5_1, name='topic_5_1'),
    path('topic-5-2', topic_5_2, name='topic_5_2'),
    path('topic-5-3', topic_5_3, name='topic_5_3'),
    path('topic-5-4', topic_5_4, name='topic_5_4'),
    path('topic-5-5', topic_5_5, name='topic_5_5'),
    path('topic-5-6', topic_5_6, name='topic_5_6'),
    path('topic-5-7', topic_5_7, name='topic_5_7'),
    path('topic-5-8', topic_5_8, name='topic_5_8'),
    path('topic-5-9', topic_5_9, name='topic_5_9'),
    path('topic-5-10', topic_5_10, name='topic_5_10'),
    path('topic-5-11', topic_5_11, name='topic_5_11'),
    path('topic-5-12', topic_5_12, name='topic_5_12'),
    path('topic-5-13', topic_5_13, name='topic_5_13'),
    path('topic-5-14', topic_5_14, name='topic_5_14'),
]

info/models.py
from django.db import models

# Create your models here.

info/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

NAME_ORGANIZATION = 'СБТ'


# Create your views here.
@login_required
def index(request):
    context = {
        'title': f'Учебный портал {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'info/index.html', context=context)


@login_required
def study(request):
    context = {
        'title': f'Доступные курсы от {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'info/study.html', context=context)


@login_required
def studying(request):
    context = {
        'title': f'Охрана труда с изменениями сентября 2022',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'info/studying.html', context=context)

info/templates/info/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

info/templates/info/header_footer.html
{% load static %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ru">
    <head>
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
        <title>{{ title }}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Учебный портал {{ name }}" />
        <meta name="author" content="Konstantin" />

        <link rel="shortcut icon" type="image/png" href="{% static 'assets/favicon.ico' %}" />

        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'info:index' %}"><img class="logo__image"
                                                                    src="{% static 'assets/favicon.ico' %}"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'info:study' %}">Моё обучение</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'studyapp:topics' %}">Выбрать курс</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">{{ user.first_name }} {{ user.last_name }}</a></li>
                        {% if user.is_superuser %}
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'authapp:register' %}">Добавить пользователя</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'authapp:logout' %}">Выход</a></li>
<!--                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>-->
                    </ul>
                </div>
            </div>
        </nav>


    {% block content %} {% endblock %}

            <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="small text-center text-muted fst-italic">СБТ &copy; Учебный центр "Охрана безопасности труда" 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

info/templates/info/index.html
{% extends 'info/header_footer.html' %}

{% load static %}

{% block content %}
 <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %});">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Охрана труда</h1>
                            <span class="subheading">Развитие технологий повышения безопасности труда, создание условий работы для сотрудников с минимальными рисками для их жизни и здоровья, оптимизация внутренних процессов управления безопасностью труда</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                  <p class="post-meta">  Добро пожаловать {{ user.first_name }} {{ user.last_name }} на учебный портал СБТ!
Здесь вы найдете лучшие инструменты для развития своих навыков и компетенций,
повышения эффективности своей работы в области охраны труда. Желаем удачи! </p>

                    <!-- Post preview-->
                    <div class="post-preview">
                        <h2 class="post-title">Текущие дела</h2>
                        <a href="{% url 'info:studying' %}">
                                <table cellpadding="0" cellspacing="0" border="0">
                            <tr>
                                <td><div><img class="logo__image"
                                                                        src="{%static 'assets/img/home-bg.jpg' %}" style="width: 100%;" border="0"/></div></td>
    <!--							<td><div class="username" onclick='fnToggleDropdown(this, true)'><a href="javascript:void(0)">Корявый Виталий Викторович</a></div></td>-->

    <!--							<td><div class="button-dropdown" onclick='fnToggleDropdown(this, true)'></div></td>-->

    <!--							<td><div class="exit-button-container"><a href="javascript:void(0)" onclick="fnLogout()" title="Выход"><i class="icon-sign-out-ico  icon-2x"></i></a></div></td>-->

                            </tr>
                        </table>



                           <h4 class="post-subtitle">Охрана труда с изменениями от сентября 2022г.</h4>

                            <p class="post-meta">
                                Пройти электронный курс
                            </p>
                        </a>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

info/templates/info/index1.html
{% load static %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ru">
    <head>
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
        <title>{{ title }}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Учебный портал {{ name }}" />
        <meta name="author" content="Konstantin" />

        <link rel="shortcut icon" type="image/png" href="{% static 'assets/favicon.ico' %}" />

        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'info:index' %}"><img class="logo__image"
                                                                    src="{% static 'assets/favicon.ico' %}"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'info:study' %}">Моё обучение</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">Помощь</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">{{ user.first_name }} {{ user.last_name }}</a></li>
                        {% if user.is_superuser %}
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'authapp:register' %}">Добавить пользователя</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'authapp:logout' %}">Выход</a></li>
<!--                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>-->
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({%static 'assets/img/home-bg.jpg' %});">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Охрана труда</h1>
                            <span class="subheading">Развитие технологий повышения безопасности труда, создание условий работы для сотрудников с минимальными рисками для их жизни и здоровья, оптимизация внутренних процессов управления безопасностью труда</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                  <p class="post-meta">  Добро пожаловать {{ user.first_name }} {{ user.last_name }} на учебный портал СБТ!
Здесь вы найдете лучшие инструменты для развития своих навыков и компетенций,
повышения эффективности своей работы в области охраны труда. Желаем удачи! </p>

                    <!-- Post preview-->
                    <div class="post-preview">
                        <h2 class="post-title">Текущие дела</h2>
                        <a href="post.html">
                                <table cellpadding="0" cellspacing="0" border="0">
                            <tr>
                                <td><div><img class="logo__image"
                                                                        src="{%static 'assets/img/home-bg.jpg' %}" style="width: 100%;" border="0"/></div></td>
    <!--							<td><div class="username" onclick='fnToggleDropdown(this, true)'><a href="javascript:void(0)">Корявый Виталий Викторович</a></div></td>-->

    <!--							<td><div class="button-dropdown" onclick='fnToggleDropdown(this, true)'></div></td>-->

    <!--							<td><div class="exit-button-container"><a href="javascript:void(0)" onclick="fnLogout()" title="Выход"><i class="icon-sign-out-ico  icon-2x"></i></a></div></td>-->

                            </tr>
                        </table>



                           <h4 class="post-subtitle">Охрана труда с изменениями от сентября 2022г.</h4>

                            <p class="post-meta">
                                Пройти электронный курс
                            </p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="small text-center text-muted fst-italic">СБТ &copy; Учебный центр "Охрана безопасности труда" 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

info/templates/info/study.html
{% extends 'info/header_footer.html' %}

{% load static %}

{% block content %}
                <!-- Page Header-->
        <header class="masthead" style="padding-top: 100px; padding-bottom: 100px">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>Доступные Вам курсы</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                                               <h2 class="post-title">Текущие дела</h2>
                        <a href="{% url 'info:studying' %}">
                                <table cellpadding="0" cellspacing="0" border="0">
                            <tr>
                                <td><div><img class="logo__image"
                                                                        src="{%static 'assets/img/home-bg.jpg' %}" style="width: 100%;" border="0"/></div></td>
    <!--							<td><div class="username" onclick='fnToggleDropdown(this, true)'><a href="javascript:void(0)">Корявый Виталий Викторович</a></div></td>-->

    <!--							<td><div class="button-dropdown" onclick='fnToggleDropdown(this, true)'></div></td>-->

    <!--							<td><div class="exit-button-container"><a href="javascript:void(0)" onclick="fnLogout()" title="Выход"><i class="icon-sign-out-ico  icon-2x"></i></a></div></td>-->

                            </tr>
                        </table>



                           <h4 class="post-subtitle">Охрана труда с изменениями от сентября 2022г.</h4>

                            <p class="post-meta">
                                Пройти электронный курс
                            </p>
                        </a>
                    </div>
                </div>
            </div>
        </article>
{% endblock %}