authapp/urls.py
from django.urls import path

from .views import login, logout, RegisterCreateView

app_name = 'authapp'

urlpatterns = [
    # path('login/', login, name='login'),
    path('', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', RegisterCreateView.as_view(), name='register'),
]

sdo/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('info.urls', namespace='info'), name='index'),
    path('info/', include('info.urls', namespace='info'), name='index'),
    path('tests/', include('tests.urls', namespace='tests'), name='test'),
    path('studyapp/', include('studyapp.urls', namespace='studyapp'), name='study'),
    # path('auth/', include('authapp.urls', namespace='authapp'), name='auth'),
    path('', include('authapp.urls', namespace='authapp'), name='auth'),
]

studyapp/urls.py
from django.urls import path

from .views import study_start, topic_1_1, topic_1_2, topic_1_3, topic_1_4, topic_1_5, topics, topic_2_1, topic_2_2, \
    topic_2_3, topic_2_4, topic_3_1, topic_3_2, topic_3_3, topic_3_4, topic_3_5, topic_3_6, topic_4_1, topic_4_2, \
    topic_4_3, topic_4_4, topic_4_5, topic_4_6, topic_4_7, topic_4_8, topic_4_9, topic_5_0, topic_5_1, topic_5_2, \
    topic_5_3, topic_5_4, topic_5_5, topic_5_6, topic_5_7, topic_5_8, topic_5_9, topic_5_10, topic_5_11, topic_5_12, \
    topic_5_13, topic_5_14, topics_b, topics_c, topics_d, topics_e

app_name = 'studyapp'

urlpatterns = [
    path('', study_start, name='study_start'),
    # path('test-a', test_a, name='test_a'),
    path('topics', topics, name='topics'),
    path('topics-b', topics_b, name='topics_b'),
    path('topics-c', topics_c, name='topics_c'),
    path('topics-d', topics_d, name='topics_d'),
    path('topics-e', topics_e, name='topics_e'),
    path('topic-1-1', topic_1_1, name='topic_1_1'),
    path('topic-1-2', topic_1_2, name='topic_1_2'),
    path('topic-1-3', topic_1_3, name='topic_1_3'),
    path('topic-1-4', topic_1_4, name='topic_1_4'),
    path('topic-1-5', topic_1_5, name='topic_1_5'),
    path('topic-2-1', topic_2_1, name='topic_2_1'),
    path('topic-2-2', topic_2_2, name='topic_2_2'),
    path('topic-2-3', topic_2_3, name='topic_2_3'),
    path('topic-2-4', topic_2_4, name='topic_2_4'),
    path('topic-3-1', topic_3_1, name='topic_3_1'),
    path('topic-3-2', topic_3_2, name='topic_3_2'),
    path('topic-3-3', topic_3_3, name='topic_3_3'),
    path('topic-3-4', topic_3_4, name='topic_3_4'),
    path('topic-3-5', topic_3_5, name='topic_3_5'),
    path('topic-3-6', topic_3_6, name='topic_3_6'),
    # path('topic-3-7', topic_3_7, name='topic_3_7'),
    # path('topic-3-8', topic_3_8, name='topic_3_8'),
    path('topic-4-1', topic_4_1, name='topic_4_1'),
    path('topic-4-2', topic_4_2, name='topic_4_2'),
    path('topic-4-3', topic_4_3, name='topic_4_3'),
    path('topic-4-4', topic_4_4, name='topic_4_4'),
    path('topic-4-5', topic_4_5, name='topic_4_5'),
    path('topic-4-6', topic_4_6, name='topic_4_6'),
    path('topic-4-7', topic_4_7, name='topic_4_7'),
    path('topic-4-8', topic_4_8, name='topic_4_8'),
    path('topic-4-9', topic_4_9, name='topic_4_9'),
    path('topic-5-0', topic_5_0, name='topic_5_0'),
    path('topic-5-1', topic_5_1, name='topic_5_1'),
    path('topic-5-2', topic_5_2, name='topic_5_2'),
    path('topic-5-3', topic_5_3, name='topic_5_3'),
    path('topic-5-4', topic_5_4, name='topic_5_4'),
    path('topic-5-5', topic_5_5, name='topic_5_5'),
    path('topic-5-6', topic_5_6, name='topic_5_6'),
    path('topic-5-7', topic_5_7, name='topic_5_7'),
    path('topic-5-8', topic_5_8, name='topic_5_8'),
    path('topic-5-9', topic_5_9, name='topic_5_9'),
    path('topic-5-10', topic_5_10, name='topic_5_10'),
    path('topic-5-11', topic_5_11, name='topic_5_11'),
    path('topic-5-12', topic_5_12, name='topic_5_12'),
    path('topic-5-13', topic_5_13, name='topic_5_13'),
    path('topic-5-14', topic_5_14, name='topic_5_14'),
]

studyapp/models.py
from django.db import models

# Create your models here.

studyapp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
NAME_ORGANIZATION = 'СБТ'


# Create your views here.
@login_required
def topics(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/topics.html', context=context)


@login_required
def study_start(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/topics_a.html', context=context)


@login_required
def topics_b(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/topics_b.html', context=context)


@login_required
def topics_c(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/topics_c.html', context=context)


@login_required
def topics_d(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/topics_d.html', context=context)


@login_required
def topics_e(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/topics_e.html', context=context)


@login_required
def topic_1_1(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_a_1.html', context=context)


@login_required
def topic_1_2(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_a_2.html', context=context)


@login_required
def topic_1_3(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_a_3.html', context=context)


@login_required
def topic_1_4(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_a_4.html', context=context)


@login_required
def topic_1_5(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_a_5.html', context=context)


@login_required
def topic_2_1(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_b_1.html', context=context)


@login_required
def topic_2_2(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_b_2.html', context=context)


@login_required
def topic_2_3(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_b_3.html', context=context)


@login_required
def topic_2_4(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_b_4.html', context=context)


@login_required
def topic_3_1(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_c_1.html', context=context)


@login_required
def topic_3_2(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_c_2.html', context=context)


@login_required
def topic_3_3(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_c_3.html', context=context)


@login_required
def topic_3_4(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_c_4.html', context=context)


@login_required
def topic_3_5(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_c_5.html', context=context)


@login_required
def topic_3_6(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_c_6.html', context=context)


# @login_required
# def topic_3_7(request):
#     context = {
#         'title': f'СДО {NAME_ORGANIZATION}',
#         'name': NAME_ORGANIZATION,
#     }
#     if request.method == 'POST':
#         pass
#     return render(request, 'studyapp/studying_c_7_not.html', context=context)
#
#
# @login_required
# def topic_3_8(request):
#     context = {
#         'title': f'СДО {NAME_ORGANIZATION}',
#         'name': NAME_ORGANIZATION,
#     }
#     if request.method == 'POST':
#         pass
#     return render(request, 'studyapp/studying_c_8.html', context=context)


@login_required
def topic_4_1(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_d_1.html', context=context)


@login_required
def topic_4_2(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_d_2.html', context=context)


@login_required
def topic_4_3(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_d_3.html', context=context)


@login_required
def topic_4_4(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_d_4.html', context=context)


@login_required
def topic_4_5(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_d_5.html', context=context)


@login_required
def topic_4_6(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_d_6.html', context=context)


@login_required
def topic_4_7(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_d_7.html', context=context)


@login_required
def topic_4_8(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_d_8.html', context=context)


@login_required
def topic_4_9(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_d_9.html', context=context)


@login_required
def topic_5_0(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_e_0.html', context=context)


@login_required
def topic_5_1(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_e_1.html', context=context)


@login_required
def topic_5_2(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_e_2.html', context=context)


@login_required
def topic_5_3(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_e_3.html', context=context)


@login_required
def topic_5_4(request):
    context = {
        'title': f'СДО {NAME_ORGANIZATION}',
        'name': NAME_ORGANIZATION,
    }
    if request.method == 'POST':
        pass
    return render(request, 'studyapp/studying_e_4.html', context=context)


@login_required
def topic_5_5(request):

studyapp/templates/studyapp/studying_e_1.html
{% extends 'info/header_footer.html' %}

{% load static %}

{% block content %}
                <!-- Page Header-->
        <header class="masthead" style="padding-top: 150px; padding-bottom: 100px;">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
<!--                    <div class="col-md-10 col-lg-8 col-xl-7">-->
                    <div style="width: 100%">
                        <div class="post-heading">
                            <h4>Электронный курс</h4>
                            <h2>Оказание первой помощи пострадавшим</h2>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <!-- Post Content-->





        <article class="mb-4">
            <div class="container px-4 px-lg-5">


                <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample" style="position: fixed; left: 10px; width: 20%;">
  Вспомогательное меню по теме
</a>


<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel">Обучение охране труда</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div>
      <b>Оказание первой помощи пострадавшим</b>
    </div>
    <div class="dropdown mt-6">
                      <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" style="white-space: pre-wrap;  width: 100%;">
Выбрать тему
      </button>


              <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="{% url 'studyapp:topic_5_0' %}" style="white-space: pre-wrap;">Введение</a></li>
        <li><a class="dropdown-item" href="{% url 'studyapp:topic_5_1' %}" style="white-space: pre-wrap;">Тема 1. Кровотечение</a></li>
        <li><a class="dropdown-item" href="{% url 'studyapp:topic_5_2' %}" style="white-space: pre-wrap;">Тема 2. Ушиб и растяжение</a></li>
        <li><a class="dropdown-item" href="{% url 'studyapp:topic_5_3' %}" style="white-space: pre-wrap;">Тема 3. Сердечный приступ (инфаркт)</a></li>
        <li><a class="dropdown-item" href="{% url 'studyapp:topic_5_4' %}" style="white-space: pre-wrap;">Тема 4. Ожоги</a></li>
        <li><a class="dropdown-item" href="{% url 'studyapp:topic_5_5' %}" style="white-space: pre-wrap;">Тема 5. Потеря сознания (обморок)</a></li>
        <li><a class="dropdown-item" href="{% url 'studyapp:topic_5_6' %}" style="white-space: pre-wrap;">Тема 6. Перелом позвоночника</a></li>
        <li><a class="dropdown-item" href="{% url 'studyapp:topic_5_7' %}" style="white-space: pre-wrap;">Тема 7. Инсульт</a></li>
        <li><a class="dropdown-item" href="{% url 'studyapp:topic_5_8' %}" style="white-space: pre-wrap;">Тема 8. Электротравма</a></li>
        <li><a class="dropdown-item" href="{% url 'studyapp:topic_5_9' %}" style="white-space: pre-wrap;">Тема 9. Перелом</a></li>
        <li><a class="dropdown-item" href="{% url 'studyapp:topic_5_10' %}" style="white-space: pre-wrap;">Тема 10. Отравление</a></li>
        <li><a class="dropdown-item" href="{% url 'studyapp:topic_5_11' %}" style="white-space: pre-wrap;">Тема 11. Отморожение</a></li>
        <li><a class="dropdown-item" href="{% url 'studyapp:topic_5_12' %}" style="white-space: pre-wrap;">Тема 12. Ранения</a></li>
        <li><a class="dropdown-item" href="{% url 'studyapp:topic_5_13' %}" style="white-space: pre-wrap;">Тема 13. Травмы</a></li>
        <li><a class="dropdown-item" href="{% url 'studyapp:topic_5_14' %}" style="white-space: pre-wrap;">Тема 14. Ампутация</a></li>
      </ul>



      <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" style="white-space: pre-wrap;">
        Тема 1. Кровотечение
      </button>
      <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="#concepts1" style="white-space: pre-wrap;">1. Артериальное кровотечение</a></li>
        <li><a class="dropdown-item" href="#concepts2" style="white-space: pre-wrap;">2. Венозное кровотечение</a></li>
        <li><a class="dropdown-item" href="#concepts3" style="white-space: pre-wrap;">3. Носовое кровотечение</a></li>
        <li><a class="dropdown-item" href="#concepts4" style="white-space: pre-wrap;">4. Капиллярное кровотечение</a></li>
      </ul>

    </div>
  </div>
</div>



                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <br>
                                               <h2 class="post-title"> <a name="concepts1"></a>Артериальное кровотечение</h2>

<p style="white-space: pre-wrap;">Кровь из артерии имеет <b>ярко-красный цвет.</b> Поскольку артериальная кровь поступает непосредственно из сердца, она может пульсировать или брызгать из раны.
<img class="logo__image" src="{% static 'image/z4.png' %}">

<b>Алгоритм действий:</b>
1. В случае значительной кровопотери <b>уложить пострадавшего с приподнятыми ногами.</b>
2. <b>Прижатием артерии в ране или в точках,</b> где ощущаются <b>удары пульса,</b> временно остановить кровотечение. Артерию следует сильно прижать <b>мякотью 2-4 пальцев или кулаком</b> к близлежащим костным образованиям до исчезноваения пульса. На конечностях точка прижатия артерии должна быть выше места кровотечения, на шее и голове – ниже раны или в ране.
3. Наложить на рану <b>давящую повязку.</b>
<img class="logo__image" src="{% static 'image/z5.png' %}">

4. Если рана глубокая, то провести <b>ее тампонаду:</b> полость раны туго заполнить стерильным бинтом или чистой тканью, затем туго перебинтовать.
5. Если давящая повязка промокает (пропитывается кровью), то повязку не снимать, а <b>поверх нее дополнительно обмотать</b> рану еще несколькими слоями бинта
или ткани, стараясь увеличить силу давления.
6. Если после наложения давящей повязки кровотечение продолжается, то в качестве
крайней меры наложить <b>кровоостанавливающий жгут.</b> Жгут можно накладывать
только на конечности выше места ранения (кроме ран сонной артерии) и как можно ближе к нему. Поврежденную конечность приподнять, под жгут подложить полотенце
или одежду пострадавшего, жгут растянуть и несколько раз обернуть вокруг
конечности, причем первый оборот должен быть самым тугим.
<b>Обязательно</b> вложить записку с указанием <b>времени наложения жгута.</b> Время, прошедшее с момента наложения жгута, не должно превышать:
• 1 час в теплое время года
• 0,5 часа – в холодное время года (обязательно утепляя конечность).
После прошедшего времени ослабить жгут (кроме случаев, когда жгут наложен на оторванной конечности). В случае возобновления обильного кровотечения наложить жгут вновь.
<img class="logo__image" src="{% static 'image/z6.png' %}">

7. Вызвать скорую медицинскую помощь или срочно доставить пострадавшего в больницу.
</p>
                                              <h2 class="post-title"> <a name="concepts2"></a>Венозное кровотечение</h2>

<p style="white-space: pre-wrap;">Кровь из вены имеет <b>темно-красный цвет.</b> Изливается непрерывным, равномерным потоком, может отмечаться пульсирование в ритме дыхания.

<b>Алгоритм действий:</b>
1. Если нет перелома, приподнять поврежденную конечность.
2. Если кровотечение достаточно сильное, то тратить время на обработку раны нельзя.
3. Прижать кровоточащую рану.
4. Наложить давящую повязку: на рану наложить несколько слоев марли, поверх нее – рулон бинта или плотный комок ваты и туго перебинтовать.
5. Нужно следить за тем, чтобы не перетянуть конечность слишком сильно (до посинения кожи ниже повязки).
<img class="logo__image" src="{% static 'image/z7.png' %}">
</p>


                                              <h2 class="post-title"> <a name="concepts3"></a>Носовое кровотечение</h2>

<p style="white-space: pre-wrap;"><b>Алгоритм действий:</b>
1. Усадить пострадавшего, слегка <b>наклонить голову вперед</b>.
<img class="logo__image" src="{% static 'image/z8.png' %}">
2. Пострадавший должен дышать ртом.
3. Сжать на <b>5-10</b> минут нос чуть выше ноздрей.
4. Кровь не глотать, сплевывать.
5. Приложить холод к переносице.
<img class="logo__image" src="{% static 'image/z9.png' %}">
6. После остановки кровотечения не тереть нос и не сморкаться в течение некоторого времени.
7. Если кровотечение из носа не остановилось в течение 15-20 минут, ввести в носовые ходы свернутые в рулончик марлевые тампоны, доставить пострадавшего в больницу.
</p>

                                              <h2 class="post-title"> <a name="concepts4"></a>Капиллярное кровотечение</h2>

<p style="white-space: pre-wrap;">Кровь <b>алого цвета,</b> вытекает маленькими каплями (медленно выделяется равномерно из всей раны).

<b>Алгоритм действий:</b>
    1. Приподнять поврежденную конечность.
    2. Промыть рану под струей воды, обработать рану дезинфицирующим раствором или помазать антисептиком кожу вокруг раны.
    3. Наложить обычную повязку или заклеить рану бактерицидным пластырем.
    4. Поврежденную конечность некоторое время держать неподвижной.
<img class="logo__image" src="{% static 'image/z10.png' %}">
</p>


                        <br>
  <div>
      <a href="{% url 'studyapp:topic_5_0' %}" class="btn btn-outline-info btn-lg" tabindex="-1" role="button" aria-disabled="true" style="margin-bottom: 5px; width: 49%; display: table-cell; vertical-align: middle">Введение</a>
      <a href="{% url 'studyapp:topic_5_2' %}" class="btn btn-outline-info btn-lg" tabindex="-1" role="button" aria-disabled="true" style="margin-bottom: 5px; width: 49%; display: table-cell; vertical-align: middle">Тема 2. Ушиб и лечение</a>
</div>

                        <br>
      <a href="{% url 'studyapp:topics_e' %}" class="btn btn-outline-info btn-lg" tabindex="-1" role="button" aria-disabled="true" style="margin-bottom: 5px; width: 100%;">К выбору темы</a>


                    </div>
                </div>
            </div>
        </article>
{% endblock %}